FROM alpine-jdk:base
LABEL maintainer="jerall7712@gmail.com"
COPY eurekaserver-0.0.1-SNAPSHOT.jar /opt/lib/eureka-server.jar
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar","/opt/lib/eureka-server.jar"]
EXPOSE 8761